if (DEFINED ENV{UNIQUE_BUILDINFO})
	add_definitions(-DSONIA_ONE_UNIQUE_BUILDINFO=$ENV{UNIQUE_BUILDINFO})
endif (DEFINED ENV{UNIQUE_BUILDINFO})

################################################################# ICU 

if (BUILD_MINGW)
    if ("${BUILD_TYPE}" STREQUAL "SHARED")
        set (ICU_TPL_DIR ${TPLS}/icu.mingw64)
    else()
        set (ICU_TPL_DIR ${TPLS}/icu.mingw64.static)
    endif()
    set (ICU_TPL_LIB ${ICU_TPL_DIR}/lib)
else()    
    set (ICU_TPL_DIR ${TPLS}/icu)
    set (ICU_TPL_LIB ${ICU_TPL_DIR}/lib64)
endif()
    
if (DEFINED ENV{ICU_INCLUDE})
	include_directories($ENV{ICU_INCLUDE})
else (DEFINED ENV{ICU_INCLUDE})
	if (DEFINED ENV{ICU_HOME})
		include_directories($ENV{ICU_HOME}/include)
    else (DEFINED ENV{ICU_HOME})
        if (WIN32)
            include_directories(${ICU_TPL_DIR}/include)
        endif()
	endif (DEFINED ENV{ICU_HOME})
endif (DEFINED ENV{ICU_INCLUDE})	

if (DEFINED ENV{ICU_LIB})
	link_directories($ENV{ICU_LIB})
else (DEFINED ENV{ICU_LIB})
	if (DEFINED ENV{ICU_HOME})
		link_directories($ENV{ICU_HOME}/lib)
    else (DEFINED ENV{ICU_HOME})
        if (WIN32)
            link_directories(${ICU_TPL_LIB})
        endif (WIN32)
	endif (DEFINED ENV{ICU_HOME})
endif (DEFINED ENV{ICU_LIB})

################################################################# ZLIB

if (DEFINED ENV{ZLIB_INCLUDE})
	include_directories($ENV{ZLIB_INCLUDE})
else (DEFINED ENV{ZLIB_INCLUDE})
	if (DEFINED ENV{ZLIB_HOME})
		include_directories($ENV{ZLIB_HOME}/include)
    else (DEFINED ENV{ZLIB_HOME})
        if (WIN32)
            include_directories(${TPLS}/zlib/include)
        endif (WIN32)
	endif (DEFINED ENV{ZLIB_HOME})
endif (DEFINED ENV{ZLIB_INCLUDE})

if (DEFINED ENV{ZLIB_LIB})
	link_directories($ENV{ZLIB_LIB})
else (DEFINED ENV{ZLIB_LIB})
	if (DEFINED ENV{ZLIB_HOME})
		link_directories($ENV{ZLIB_HOME}/lib)
    else (DEFINED ENV{ZLIB_HOME})
        
	endif (DEFINED ENV{ZLIB_HOME})
endif (DEFINED ENV{ZLIB_LIB})

################################################################# OPENSSL

if (DEFINED ENV{OPENSSL_INCLUDE})
	include_directories($ENV{OPENSSL_INCLUDE})
else (DEFINED ENV{OPENSSL_INCLUDE})
	if (DEFINED ENV{OPENSSL_HOME})
		include_directories($ENV{OPENSSL_HOME}/include)
	else (DEFINED ENV{OPENSSL_HOME})
        include_directories(${TPLS}/openssl/include)
	endif (DEFINED ENV{OPENSSL_HOME})
endif (DEFINED ENV{OPENSSL_INCLUDE})

if (DEFINED ENV{OPENSSL_LIB})
	link_directories($ENV{OPENSSL_LIB})
else (DEFINED ENV{OPENSSL_LIB})
	if (DEFINED ENV{OPENSSL_HOME})
		link_directories($ENV{OPENSSL_HOME}/lib)
	else (DEFINED ENV{OPENSSL_HOME})
		if (WIN32)
			link_directories(${TPLS}/openssl/bin.mingw64)
		endif (WIN32)
	endif (DEFINED ENV{OPENSSL_HOME})
endif (DEFINED ENV{OPENSSL_LIB})

################################################################# BOOST 
if (DEFINED ENV{BOOST_INCLUDE})
    include_directories($ENV{BOOST_INCLUDE})
else (DEFINED ENV{BOOST_INCLUDE})
	if (DEFINED ENV{BOOST_HOME})
		include_directories($ENV{BOOST_HOME}/include)
    else (DEFINED ENV{BOOST_HOME})
        include_directories(${TPLS}/boost/include)
	endif (DEFINED ENV{BOOST_HOME})
endif (DEFINED ENV{BOOST_INCLUDE})

if (DEFINED ENV{BOOST_LIB})
	link_directories($ENV{BOOST_LIB})
else (DEFINED ENV{BOOST_LIB})
	if (DEFINED ENV{BOOST_HOME})
		link_directories($ENV{BOOST_HOME}/lib)
    else (DEFINED ENV{BOOST_HOME})
		link_directories(${TPLS}/boost/lib)
	endif (DEFINED ENV{BOOST_HOME})
endif (DEFINED ENV{BOOST_LIB})

if ("${BUILD_TYPE}" STREQUAL "SHARED")
    set(SONIA_C_AND_CXX_COMMON "${SONIA_C_AND_CXX_COMMON} -DBOOST_LOG_DYN_LINK -DBOOST_STACKTRACE_DYN_LINK")
    set(BOOST_LIB_TYPE_SUFFIX "")
else()
    set(BOOST_LIB_TYPE_SUFFIX ".a")
endif ()

set(BOOST_SUFFIX "${BOOST_BUILD_INFIX}-mt${BOOST_LIB_SUFFIX}${BOOST_LIB_TYPE_SUFFIX}")

if (CMAKE_SYSTEM_NAME STREQUAL "Windows")
    set(SONIA_C_AND_CXX_COMMON "${SONIA_C_AND_CXX_COMMON} -DBOOST_USE_WINDOWS_H")
endif ()

set (BOOST_TEST_LIB boost_test_exec_monitor${BOOST_SUFFIX} boost_unit_test_framework${BOOST_SUFFIX})
set (BOOST_LOG boost_log${BOOST_SUFFIX})
set (BOOST_LOG_SETUP boost_log_setup${BOOST_SUFFIX})
set (BOOST_THREAD boost_thread${BOOST_SUFFIX})
set (BOOST_SYSTEM boost_system${BOOST_SUFFIX})
set (BOOST_SERIALIZATION boost_serialization${BOOST_SUFFIX})
set (BOOST_PROGRAM_OPTIONS boost_program_options${BOOST_SUFFIX})
set (BOOST_FILESYSTEM boost_filesystem${BOOST_SUFFIX})
set (BOOST_REGEX boost_regex${BOOST_SUFFIX})
set (BOOST_CHRONO boost_chrono${BOOST_SUFFIX})
set (BOOST_LOCALE boost_locale${BOOST_SUFFIX})
set (BOOST_RANDOM boost_random${BOOST_SUFFIX})
set (BOOST_CONTEXT boost_context${BOOST_SUFFIX})
set (BOOST_FIBERS boost_fiber${BOOST_SUFFIX})

if (CMAKE_SYSTEM_NAME STREQUAL "Windows")
    if ("${BUILD_TYPE}" STREQUAL "SHARED")
        set (BOOST_STACKTRACE boost_stacktrace_windbg${BOOST_SUFFIX})
    else()
        set (BOOST_STACKTRACE dbgeng)
    endif()
elseif (CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    if ("${BUILD_TYPE}" STREQUAL "SHARED")
        set (BOOST_STACKTRACE boost_stacktrace_basic${BOOST_SUFFIX})
    else()
        set (BOOST_STACKTRACE)
        set (SONIA_C_AND_CXX_COMMON "${SONIA_C_AND_CXX_COMMON} -DBOOST_STACKTRACE_GNU_SOURCE_NOT_REQUIRED")
    endif()
else ()
    set (BOOST_STACKTRACE)
endif ()
################################################################# DEBUG 

if (DEFINED ENV{GCC_DEBUG_INFO})
	set(SONIA_C_AND_CXX_COMMON "${SONIA_C_AND_CXX_COMMON} -g")
else()
    set(SONIA_C_AND_CXX_COMMON "${SONIA_C_AND_CXX_COMMON} -DNDEBUG")
endif (DEFINED ENV{GCC_DEBUG_INFO})

if (DEFINED USE_VALGRIND)
    set(ignoreMe "${USE_VALGRIND}")
    set (SONIA_C_AND_CXX_COMMON "${SONIA_C_AND_CXX_COMMON} -DBOOST_USE_VALGRIND")
endif ()

if (CMAKE_SYSTEM_NAME STREQUAL "Windows")
    set(PLATFORM_LIBS -lws2_32 -lmswsock)
elseif (CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(SONIA_C_AND_CXX_COMMON "${SONIA_C_AND_CXX_COMMON} -fPIC")
    set(PLATFORM_LIBS -lrt -ldl -lpthread)
elseif (CMAKE_SYSTEM_NAME STREQUAL "Darwin")
	set(SONIA_C_AND_CXX_COMMON "${SONIA_C_AND_CXX_COMMON} -fPIC -fvisibility=hidden")
endif ()


#libraries
set (ZLIB z)
set (BZLIB bz2)
set (OPENSSL ssl crypto)


#	set (WHOPR_FLAG "-flto")
set (SONIA_C_AND_CXX_COMMON "${SONIA_C_AND_CXX_COMMON} -DBOOST_THROW_EXCEPTION_CURRENT_FUNCTION=__FUNCTION__ -DBOOST_ASSERT_CURRENT_FUNCTION_NAME=__FUNCTION__ -DBOOST_ASSERT_MSG_CURRENT_FUNCTION_NAME=__FUNCTION__ -D_FILE_OFFSET_BITS=64 -O3 -finput-charset=UTF-8 ${WHOPR_FLAG} -Wno-deprecated -fdata-sections -ffunction-sections"
)

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${SONIA_C_AND_CXX_COMMON}")   
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${SONIA_C_AND_CXX_COMMON} -std=c++2a -Wno-reorder -Wno-unused-local-typedefs")

